# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: iOS 14.5 SDK

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.0rc1
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0-rc.1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+git://github.com/kritantadev/ktool@python3.10
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Setting up run dependencies
      run: |
        wget https://headers.krit.me/dsc/14.7/14.7-extracted.zip
        unzip 14.7-extracted.zip
    - name: Building SDK
      run: |
        python sdk_builder.py
    - name: Compressing Artifact
      run: | 
        zip -r fws.zip .sdkbuilder
    - name: Upload Zipped PrivateFrameworks
      uses: actions/upload-artifact@v2.2.4
      with:
        name: PrivateFrameworks
        path: fws.zip
