# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: SDKs

on:
  push:
    branches: [ master, ios15 ]

jobs:
  build:
    strategy:
      matrix:
        version:
          - "15.0"

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.5'
    - name: Install blacktop/ipsw
      run: |
        brew install blacktop/tap/ipsw
    - name: Downloading IPSW
      run: |
        ipsw download ipsw --version ${{ matrix.version }} --device iPhone10,3
    - name: Extracting dyld_shared_cache from ipsw
      run: |
        unzip iPhone10,3,iPhone10,6_15.0_19A346_Restore.ipsw 
        mkdir dmg
        hdiutil attach 018-80055-001.dmg -mountroot $PWD/dmg
        cp dmg/Sky19A346.D22D221OS/System/Library/Caches/com.apple.dyld/* .
    - name: Set up python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install progressbar2 git+git://github.com/kritantadev/ktool.git git+git://github.com/arandomdev/dyldextractor.git
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Extracting binaries from dyld shared cache
      run: |
        dyldex_all dyld_shared_cache_arm64
        mv binaries/System ./
    - name: Building SDK
      run: |
        python sdk_builder.py
    - name: Compressing Artifact
      run: | 
        mv .sdkbuilder/System/Library/Frameworks ./Frameworks
        mv .sdkbuilder/System/Library/PrivateFrameworks ./PrivateFrameworks
        zip -r SDK.zip Frameworks/ PrivateFrameworks/
    - name: Upload Zipped PrivateFrameworks
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ${{ matrix.version }}-SDK.zip
        path: SDK.zip


  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Create Release          # create a new release v1
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 0.19.0-15.0
          release_name: ktool 0.18.0 | iOS 15 SDK
          draft: false
          prerelease: false
      - name: Attach binaries to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          assets=()
          for asset in ./*; do               #loop the assets in the bin folder
            if [ -d "$asset" ]
            then
              zip -r $asset.zip $asset/
              assets+=("-a" "$asset.zip")
            fi
          done
          hub release edit "${assets[@]}" -m "iOS 15 SDK" "0.19.0-15.0" 
